"""add should_go_outside column to precipitation

Revision ID: 4c89b11ef8fa
Revises: ce7517f90a3b
Create Date: 2026-04-19 19:13:40.085038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c89b11ef8fa'
down_revision: Union[str, Sequence[str], None] = 'ce7517f90a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('precipitation', sa.Column('should_go_outside', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('precipitation', 'should_go_outside')
    # ### end Alembic commands ###
